### ISSUE TITLE
storytracker "your requests" bug

### ISSUE THREAD

**Issue by jer1my** [jsmestad/story_tracker#12]
Once your requests numbers get high enough the nav gets wonky (see attached screenshot).
Saw this in Chrome(Version 45.0.2454.99 (64-bit)) on Mac (OSX Yosemite v10.10.5)

![yourrequestsbug](https://cloud.githubusercontent.com/assets/2568006/10081486/55ebbefe-62b2-11e5-999c-7937a572ca60.png)

**Comment by jsmestad** [comment]
This is resolved in latest `develop`
